### ISSUE TITLE
Android 14 support

### ISSUE THREAD

**Issue by jason-eu** [symbuzzer/livebootmodule#4] opened 2023-11-29 15:34 UTC
The module is currently incompatible with Android 14, I guess this is obvious with the changes done, but I haven't seen an update to the module posted, so I thought I might as well.

**Comment by symbuzzer** [comment] 2023-11-29 17:34
I can't try it because my device doesn't have the Android 14 update. I think there will be an update in December.

Could you download Chainfire's LiveBoot application from Google Play Store and try whether it works?

**Comment by jason-eu** [comment] 2023-11-30 06:11
It causes random bootloops.

My apologies, I thought you were on a custom ROM.

**Comment by niazlv** [comment] 2023-12-01 01:38
Yep. Error remains on LiveBoot and doesn't work correctly. Test mode don't work and verbose mode doesn't enabled after reboot. 
Android 14, oneui 6, samsung s21 ultra. Magisk(26401).

**Comment by symbuzzer** [comment] 2023-12-01 03:16
So we will wait Chainfire to fix app before probably

**Comment by symbuzzer** [comment] 2024-03-16 09:06
@jason-eu @niazlv Can you check lates 2.0.0 on Android 14 and report here please?

**Comment by jason-eu** [comment] 2024-03-16 09:10
Sorry mate, I'm no longer on A14 at the moment.

**Comment by SubSpaceManeuvers** [comment] 2024-03-16 23:23
> @jason-eu @niazlv Can you check lates 2.0.0 on Android 14 and report here please?

A14 here, I'll gladly pick up that thread and pull it. Will report back shortly.

**Comment by SubSpaceManeuvers** [comment] 2024-03-16 23:45
> @jason-eu @niazlv Can you check lates 2.0.0 on Android 14 and report here please?

Confirmed working on A14 March 2024 revision on a Pixel 8 Pro, Magisk Delta (27001).

**Comment by theundermind** [comment] 2024-03-17 02:20
Working on OOS 14.0 OnePlus 12

**Comment by ilhan-athn7** [comment] 2024-03-17 09:36
Working on Android 14 CrDroid, Xiaomi MI 8 SE

**Comment by symbuzzer** [comment] 2024-03-17 13:03
Thanks to everyone, closing...

**Closed** 2024-03-17 13:03 UTC
